[workspace]
members = ["crates/i18n-fs-core", "crates/i18n-fs-wasm"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.82"
license = "MIT"
repository = "https://github.com/iamaliybi/i18n-fs"
authors = ["iamaliybi"]

[workspace.dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", features = ["preserve_order"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
