/**
 * The `build` command: writes everything the runtimes need into `.i18n-fs/`.
 *
 * Three artefacts, each answering a question a runtime cannot answer itself:
 *
 * - `config.mjs`     the resolved snapshot, because neither the Edge runtime
 *                    nor WebAssembly can import `i18n-fs.config.ts`.
 * - `manifest.json`  a content hash per namespace, because files under
 *                    `public/` are not fingerprinted and so cannot otherwise be
 *                    cached immutably by the browser.
 * - `messages.d.ts`  the key registry, so `useTranslation` can be typed.
 *
 * Everything written here is derived and deterministic: the same inputs produce
 * byte-identical output, so `.i18n-fs/` can be committed or ignored as the
 * project prefers without producing noise either way.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ResolvedI18nFsConfig } from '../config.js';
import type { NamespaceEntry } from '../core/types.js';

/** A namespace's keys, as gathered by the check pass. */
export interface NamespaceKeys {
	locale: string;
	namespace: string;
	hash: string;
	entries: Map<string, NamespaceEntry['kind']>;
}

const HEADER = `// Generated by i18n-fs. Do not edit.\n// Run \`i18n-fs build\` to regenerate.\n`;

/** The output directory for generated artefacts. */
export function outputDir(cwd: string, out?: string): string {
	return join(cwd, out ?? '.i18n-fs');
}

function stableStringify(value: unknown): string {
	return JSON.stringify(value, null, '\t');
}

/** `{ "<locale>": { "<namespace>": "<hash>" } }`, with sorted keys. */
export function buildManifest(namespaces: NamespaceKeys[]): Record<string, Record<string, string>> {
	const manifest: Record<string, Record<string, string>> = {};

	for (const item of [...namespaces].sort(
		(a, b) => a.locale.localeCompare(b.locale) || a.namespace.localeCompare(b.namespace),
	)) {
		(manifest[item.locale] ??= {})[item.namespace] = item.hash;
	}

	return manifest;
}

function quote(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function union(values: string[]): string {
	// `never` rather than an empty union: it makes the corresponding lookup a
	// type error, which is the accurate statement when a scope has no keys of
	// that shape.
	return values.length ? values.map(quote).join(' | ') : 'never';
}

/**
 * The typed key registry.
 *
 * Normally generated from the default locale alone: it is the single source of
 * truth for what keys exist, and `check` is what guarantees the others match
 * it. Generating from the union would then type keys that are missing where
 * they are used.
 *
 * `compareLocales: false` withdraws that guarantee, so the registry has to stop
 * relying on it. There the union is what is true — these keys exist in some
 * locale — and it is the only version that compiles: a project whose German
 * tree has keys the English one does not would otherwise get a type error on
 * every one of them, which would make the option useless to the projects it
 * exists for.
 *
 * The trade is stated rather than hidden. With the union, a key present only in
 * German compiles on a page rendered in English, and falls back at runtime the
 * way any missing key does — reported with `KEY_NOT_FOUND`, never filled in
 * from another language.
 */
export function buildTypes(
	config: ResolvedI18nFsConfig,
	namespaces: NamespaceKeys[],
	scopesByNamespace: Map<string, string[]>,
): string {
	const source = config.compareLocales
		? namespaces
				.filter((item) => item.locale === config.defaultLocale)
				.sort((a, b) => a.namespace.localeCompare(b.namespace))
		: mergeLocales(namespaces);

	/**
	 * Whether a path sits inside a list.
	 *
	 * A list of ten strings is also ten indexed keys and one scope. Typing them
	 * would bury the real keys in numeric noise, and `t.array(key)[0]` is the way
	 * to reach an element anyway. They stay resolvable at runtime; they are just
	 * not part of the typed surface.
	 */
	const insideList = (entries: NamespaceKeys['entries'], path: string): boolean => {
		const parts = path.split('.');
		for (let i = 1; i < parts.length; i += 1) {
			if (entries.get(parts.slice(0, i).join('.')) === 'list') return true;
		}
		return false;
	};

	const lines: string[] = [
		HEADER,
		"import type {} from 'i18n-fs';",
		'',
		"declare module 'i18n-fs' {",
		'\t/**',
		'\t * Every namespace, the scopes inside it, and the keys reachable from',
		`\t * each scope. Generated from ${
			config.compareLocales ? 'the default locale' : 'every locale, merged'
		}.`,
		'\t */',
		'\tinterface MessageRegistry {',
	];

	for (const item of source) {
		lines.push(`\t\t${quote(item.namespace)}: {`);

		const scopes = (scopesByNamespace.get(item.namespace) ?? ['']).filter(
			(scope) => item.entries.get(scope) !== 'list' && !insideList(item.entries, scope),
		);

		for (const scope of scopes) {
			const prefix = scope ? `${scope}.` : '';
			const text: string[] = [];
			const list: string[] = [];

			for (const [key, kind] of item.entries) {
				if (!key.startsWith(prefix)) continue;
				if (insideList(item.entries, key)) continue;
				const relative = key.slice(prefix.length);
				// Only keys directly reachable from this scope; a key under a
				// deeper scope is reachable from that scope instead.
				if (!relative) continue;
				(kind === 'list' ? list : text).push(relative);
			}

			text.sort();
			list.sort();

			lines.push(`\t\t\t${quote(scope)}: { text: ${union(text)}; list: ${union(list)} };`);
		}

		lines.push('\t\t};');
	}

	if (!source.length) {
		lines.push('\t\t// No namespaces found for the default locale.');
	}

	lines.push('\t}', '}', '');

	return lines.join('\n');
}

/**
 * One entry per namespace, holding every key any locale defines for it.
 *
 * Used only when locales are not compared. A key of the same name has to have
 * one shape, so the first locale to define it wins and later disagreements are
 * left alone — with comparison off, nothing has established which of the two is
 * correct, and inventing an answer here would be worse than typing it as
 * whichever came first. `check --compare-locales` is how to find them.
 */
function mergeLocales(namespaces: NamespaceKeys[]): NamespaceKeys[] {
	const merged = new Map<string, NamespaceKeys>();

	// Sorted first, so "the first locale to define it" is a property of the
	// data rather than of the order the filesystem happened to be walked in.
	for (const item of [...namespaces].sort(
		(a, b) => a.namespace.localeCompare(b.namespace) || a.locale.localeCompare(b.locale),
	)) {
		const existing = merged.get(item.namespace);

		if (!existing) {
			merged.set(item.namespace, { ...item, entries: new Map(item.entries) });
			continue;
		}

		for (const [key, kind] of item.entries) {
			if (!existing.entries.has(key)) existing.entries.set(key, kind);
		}
	}

	return [...merged.values()];
}

/** The resolved configuration, as an ES module every runtime can import. */
export function buildConfigModule(config: ResolvedI18nFsConfig): string {
	return `${HEADER}\n/** @type {import('i18n-fs').ResolvedI18nFsConfig} */\nexport default ${stableStringify(config)};\n`;
}

/** Write all three artefacts. Returns the paths written, for reporting. */
export async function writeArtefacts(
	dir: string,
	config: ResolvedI18nFsConfig,
	namespaces: NamespaceKeys[],
	scopesByNamespace: Map<string, string[]>,
): Promise<string[]> {
	await mkdir(dir, { recursive: true });

	const files: [string, string][] = [
		['config.mjs', buildConfigModule(config)],
		['manifest.json', `${stableStringify(buildManifest(namespaces))}\n`],
		['messages.d.ts', buildTypes(config, namespaces, scopesByNamespace)],
	];

	for (const [name, contents] of files) {
		await writeFile(join(dir, name), contents, 'utf8');
	}

	return files.map(([name]) => join(dir, name));
}
