// Measures what `i18n-fs` costs a visitor, and writes the numbers into the
// README.
//
// The numbers are generated rather than typed because typed ones rot: a table
// claiming 55.7 KB long after the binary grew is worse than no table, since a
// reader has no way to tell. Everything here is read off artefacts that were
// just built — nothing is remembered from a previous run, and nothing is
// estimated.
//
// Run `npm run measure` after `npm run bootstrap && npm run example`.
//
// `--check` compares instead of writing, and is what CI runs: the documented
// sizes have to equal the sizes of the binaries that were just built, so a
// change that grows the download cannot land while the README still advertises
// the old figure. The date stamp is informational and is not compared — it says
// when a human last refreshed the page, not whether the numbers are true.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { brotliCompressSync, constants, gzipSync } from 'node:zlib';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = join(root, 'packages', 'i18n-fs');

const VERSION = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).version;

const START = '<!-- measured:start -->';
const END = '<!-- measured:end -->';

function walk(dir, found = []) {
	if (!existsSync(dir)) return found;

	for (const entry of readdirSync(dir)) {
		const path = join(dir, entry);
		if (statSync(path).isDirectory()) walk(path, found);
		else found.push(path);
	}
	return found;
}

/** Raw, gzip and brotli sizes of a file, in bytes. */
function sizes(pathOrBytes) {
	const bytes = Buffer.isBuffer(pathOrBytes) ? pathOrBytes : readFileSync(pathOrBytes);

	return {
		raw: bytes.length,
		gzip: gzipSync(bytes, { level: 9 }).length,
		// Quality 11 is what a CDN serves precompressed assets at, so this is the
		// number a real visitor actually receives.
		brotli: brotliCompressSync(bytes, {
			params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
		}).length,
	};
}

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;

// --- the three binaries, as built ------------------------------------------

const BINARIES = [
	['edge', 'the proxy, on every request', 'server-side — never downloaded'],
	['browser', 'Client Components', 'downloaded, and only when one is used'],
	['node', 'Server Components and the CLI', 'read from disk — never downloaded'],
];

const binaries = [];

for (const [name, used, who] of BINARIES) {
	const file = join(pkg, 'wasm', name, 'i18n_fs_wasm_bg.wasm');

	if (existsSync(file)) {
		binaries.push({ name, used, who, ...sizes(file) });
		continue;
	}

	// The edge and node binaries are embedded as base64 and the `.wasm` itself is
	// deleted, so the module that carries them is asked for the bytes rather than
	// the file being read. Importing it beats matching the literal with a regex:
	// it measures what the package actually ships.
	const embedded = join(pkg, 'wasm', name, 'bytes.mjs');
	if (!existsSync(embedded)) throw new Error(`no ${name} binary — run \`npm run bootstrap\``);

	const { wasmBytes } = await import(pathToFileURL(embedded).href);
	binaries.push({ name, used, who, ...sizes(Buffer.from(wasmBytes)) });
}

// --- what an example app actually ships ------------------------------------

const example = join(root, 'examples', 'next-15-middleware', '.next', 'static');
const built = existsSync(example);

let shipped = null;

if (built) {
	const files = walk(example);
	const wasm = files.find((f) => f.endsWith('.wasm'));

	if (wasm) {
		// Only the binary, deliberately.
		//
		// The first version of this added every JavaScript chunk that mentioned
		// the binary, on the grounds that a visitor downloads those too. But a
		// bundler puts the loader in a chunk beside application code, so that
		// attributed the example's own pages to this package — and the figure
		// moved when the example changed, which is how the mistake surfaced. A
		// number that grows because somebody edited a demo is not measuring the
		// package.
		//
		// The binary is exactly attributable and dominates the cost; the loader
		// that instantiates it is a couple of kilobytes folded into a chunk that
		// exists anyway.
		shipped = { wasm: sizes(wasm) };
	}
}

// --- the table -------------------------------------------------------------

const stamp = new Date().toISOString().slice(0, 10);

const lines = [
	START,
	'',
	`<!-- Generated by \`npm run measure\`. Do not edit by hand. -->`,
	'',
	`**checked_at: ${stamp} · i18n-fs ${VERSION}**`,
	'',
	'| what | when it is downloaded | gzip | brotli |',
	'| --- | --- | --- | --- |',
];

const browser = binaries.find((b) => b.name === 'browser');

if (shipped) {
	lines.push(
		`| **Client Components** — the WebAssembly binary | only when a Client Component calls \`useTranslation\` | **${kb(shipped.wasm.gzip)}** | **${kb(shipped.wasm.brotli)}** |`,
	);
} else {
	lines.push(
		`| **Client Components** — WebAssembly | only when a Client Component calls \`useTranslation\` | **${kb(browser.gzip)}** | **${kb(browser.brotli)}** |`,
	);
}

lines.push(
	'| **Server Components only** | never — nothing is sent to the browser | **0 KB** | **0 KB** |',
	'| **The proxy** | never — it runs on the server | **0 KB** | **0 KB** |',
	'',
	'Sizes of every binary, including the ones a visitor never receives:',
	'',
	'| binary | used by | downloaded? | raw | gzip | brotli |',
	'| --- | --- | --- | --- | --- | --- |',
);

for (const b of binaries) {
	lines.push(
		`| \`${b.name}\` | ${b.used} | ${b.who} | ${kb(b.raw)} | ${kb(b.gzip)} | ${kb(b.brotli)} |`,
	);
}

if (shipped) {
	lines.push(
		'',
		`Taken from the built \`examples/next-15-middleware\`, which uses client ` +
			`translations. The JavaScript that instantiates the binary is a couple of ` +
			`kilobytes and is folded into a chunk the page loads anyway.`,
	);
}

lines.push('', END);

const table = lines.join('\n');

const readme = join(root, 'README.md');
const text = readFileSync(readme, 'utf8');

if (!text.includes(START) || !text.includes(END)) {
	throw new Error(`README.md has no ${START} / ${END} markers to write between`);
}

const before = text.slice(0, text.indexOf(START));
const after = text.slice(text.indexOf(END) + END.length);

if (process.argv.includes('--check')) {
	const documented = text.slice(text.indexOf(START), text.indexOf(END) + END.length);

	// Every row except the stamp line, which is a date rather than a measurement.
	const rows = (block) =>
		block.split(/\r?\n/).filter((line) => line.startsWith('|') && !line.includes('| --- |'));

	/** The row with its numbers removed, so wording is compared exactly. */
	const shape = (line) => line.replace(/[\d.]+ KB/g, '<size>');
	const numbers = (line) => [...line.matchAll(/([\d.]+) KB/g)].map(([, n]) => Number(n));

	const was = rows(documented);
	const now = rows(table);
	const problems = [];

	if (was.length !== now.length) {
		problems.push(`the table has ${was.length} rows; the measurement produced ${now.length}`);
	}

	for (let i = 0; i < Math.min(was.length, now.length); i += 1) {
		if (shape(was[i]) !== shape(now[i])) {
			problems.push(`row ${i + 1} no longer describes the same thing:\n    ${was[i]}\n    ${now[i]}`);
			continue;
		}

		const documentedSizes = numbers(was[i]);
		const measuredSizes = numbers(now[i]);
		const label = was[i].split('|')[1].trim();

		for (let j = 0; j < documentedSizes.length; j += 1) {
			// The Rust toolchain is not byte-identical across platforms: the same
			// commit built on Linux and on Windows differs by a few tenths of a
			// kilobyte, and requiring an exact match would make this fail depending
			// on who last ran it — which teaches people to ignore it.
			//
			// Wide enough for that, and far too narrow to hide anything worth
			// knowing: the change that prompted this section was 34 KB.
			const allowed = Math.max(1, documentedSizes[j] * 0.02);

			if (Math.abs(documentedSizes[j] - measuredSizes[j]) > allowed) {
				problems.push(
					`${label}: README says ${documentedSizes[j]} KB, the build measures ${measuredSizes[j]} KB`,
				);
			}
		}
	}

	if (problems.length) {
		console.error('README.md advertises sizes that the built binaries do not have:\n');
		for (const problem of problems) console.error(`  - ${problem}`);
		console.error('\nRun `npm run measure` and commit the result.');
		process.exit(1);
	}

	console.log(`README sizes match the built binaries (i18n-fs ${VERSION}).`);
	process.exit(0);
}

writeFileSync(readme, before + table + after);

console.log(`Measured i18n-fs ${VERSION} on ${stamp}:`);
for (const b of binaries) console.log(`  ${b.name.padEnd(8)} ${kb(b.gzip).padStart(9)} gzip`);
if (shipped) console.log(`  a client page downloads ${kb(shipped.wasm.gzip)} gzip of WebAssembly`);
else console.log('  (run `npm run example` first to measure what an app ships)');
