// Measures what `i18n-fs` costs a visitor, and writes the numbers into the
// README.
//
// The numbers are generated rather than typed because typed ones rot: a table
// claiming 55.7 KB long after the binary grew is worse than no table, since a
// reader has no way to tell. Everything here is read off artefacts that were
// just built — nothing is remembered from a previous run, and nothing is
// estimated.
//
// Run `npm run measure` after `npm run bootstrap && npm run example`.
//
// `--check` compares instead of writing, and is what CI runs: the documented
// sizes have to equal the sizes of the binaries that were just built, so a
// change that grows the download cannot land while the README still advertises
// the old figure. The date stamp is informational and is not compared — it says
// when a human last refreshed the page, not whether the numbers are true.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { brotliCompressSync, constants, gzipSync } from 'node:zlib';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = join(root, 'packages', 'i18n-fs');

const VERSION = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).version;

const START = '<!-- measured:start -->';
const END = '<!-- measured:end -->';

function walk(dir, found = []) {
	if (!existsSync(dir)) return found;

	for (const entry of readdirSync(dir)) {
		const path = join(dir, entry);
		if (statSync(path).isDirectory()) walk(path, found);
		else found.push(path);
	}
	return found;
}

/** Raw, gzip and brotli sizes of a file, in bytes. */
function sizes(pathOrBytes) {
	const bytes = Buffer.isBuffer(pathOrBytes) ? pathOrBytes : readFileSync(pathOrBytes);

	return {
		raw: bytes.length,
		gzip: gzipSync(bytes, { level: 9 }).length,
		// Quality 11 is what a CDN serves precompressed assets at, so this is the
		// number a real visitor actually receives.
		brotli: brotliCompressSync(bytes, {
			params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
		}).length,
	};
}

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;

// --- the three binaries, as built ------------------------------------------

const BINARIES = [
	['edge', 'the proxy, on every request', 'server-side — never downloaded'],
	['browser', 'Client Components', 'downloaded, and only when one is used'],
	['node', 'Server Components and the CLI', 'read from disk — never downloaded'],
];

const binaries = [];

for (const [name, used, who] of BINARIES) {
	const file = join(pkg, 'wasm', name, 'i18n_fs_wasm_bg.wasm');

	if (existsSync(file)) {
		binaries.push({ name, used, who, ...sizes(file) });
		continue;
	}

	// The edge and node binaries are embedded as base64 and the `.wasm` itself is
	// deleted, so the module that carries them is asked for the bytes rather than
	// the file being read. Importing it beats matching the literal with a regex:
	// it measures what the package actually ships.
	const embedded = join(pkg, 'wasm', name, 'bytes.mjs');
	if (!existsSync(embedded)) throw new Error(`no ${name} binary — run \`npm run bootstrap\``);

	const { wasmBytes } = await import(pathToFileURL(embedded).href);
	binaries.push({ name, used, who, ...sizes(Buffer.from(wasmBytes)) });
}

// --- what an example app actually ships ------------------------------------

const example = join(root, 'examples', 'next-15-middleware', '.next', 'static');
const built = existsSync(example);

let shipped = null;

if (built) {
	const files = walk(example);
	const wasm = files.find((f) => f.endsWith('.wasm'));

	if (wasm) {
		// The glue is whichever JavaScript chunks name the binary. They are what a
		// visitor downloads alongside it, so leaving them out would understate the
		// cost.
		const glue = files.filter(
			(f) => f.endsWith('.js') && readFileSync(f, 'utf8').includes('i18n_fs_wasm_bg'),
		);

		const total = [wasm, ...glue].reduce(
			(sum, file) => {
				const s = sizes(file);
				return { raw: sum.raw + s.raw, gzip: sum.gzip + s.gzip, brotli: sum.brotli + s.brotli };
			},
			{ raw: 0, gzip: 0, brotli: 0 },
		);

		shipped = { wasm: sizes(wasm), glueCount: glue.length, total };
	}
}

// --- the table -------------------------------------------------------------

const stamp = new Date().toISOString().slice(0, 10);

const lines = [
	START,
	'',
	`<!-- Generated by \`npm run measure\`. Do not edit by hand. -->`,
	'',
	`**checked_at: ${stamp} · i18n-fs ${VERSION}**`,
	'',
	'| what | when it is downloaded | gzip | brotli |',
	'| --- | --- | --- | --- |',
];

const browser = binaries.find((b) => b.name === 'browser');

if (shipped) {
	lines.push(
		`| **Client Components** — WebAssembly + loader | only when a Client Component calls \`useTranslation\` | **${kb(shipped.total.gzip)}** | **${kb(shipped.total.brotli)}** |`,
	);
} else {
	lines.push(
		`| **Client Components** — WebAssembly | only when a Client Component calls \`useTranslation\` | **${kb(browser.gzip)}** | **${kb(browser.brotli)}** |`,
	);
}

lines.push(
	'| **Server Components only** | never — nothing is sent to the browser | **0 KB** | **0 KB** |',
	'| **The proxy** | never — it runs on the server | **0 KB** | **0 KB** |',
	'',
	'Sizes of every binary, including the ones a visitor never receives:',
	'',
	'| binary | used by | downloaded? | raw | gzip | brotli |',
	'| --- | --- | --- | --- | --- | --- |',
);

for (const b of binaries) {
	lines.push(
		`| \`${b.name}\` | ${b.used} | ${b.who} | ${kb(b.raw)} | ${kb(b.gzip)} | ${kb(b.brotli)} |`,
	);
}

if (shipped) {
	lines.push(
		'',
		`Measured from the built \`examples/next-15-middleware\`, which uses client translations: ` +
			`the binary is ${kb(shipped.wasm.gzip)} gzip and ${shipped.glueCount} JavaScript ` +
			`${shipped.glueCount === 1 ? 'chunk names' : 'chunks name'} it.`,
	);
}

lines.push('', END);

const table = lines.join('\n');

const readme = join(root, 'README.md');
const text = readFileSync(readme, 'utf8');

if (!text.includes(START) || !text.includes(END)) {
	throw new Error(`README.md has no ${START} / ${END} markers to write between`);
}

const before = text.slice(0, text.indexOf(START));
const after = text.slice(text.indexOf(END) + END.length);

if (process.argv.includes('--check')) {
	const documented = text.slice(text.indexOf(START), text.indexOf(END) + END.length);

	// Every row except the stamp line, which is a date rather than a measurement.
	const rows = (block) =>
		block
			.split(/\r?\n/)
			.filter((line) => line.startsWith('|') && !line.includes('| --- |'))
			.join('\n');

	if (rows(documented) !== rows(table)) {
		console.error('README.md advertises sizes that the built binaries do not have.\n');
		console.error('documented:');
		console.error(rows(documented));
		console.error('\nmeasured:');
		console.error(rows(table));
		console.error('\nRun `npm run measure` and commit the result.');
		process.exit(1);
	}

	console.log(`README sizes match the built binaries (i18n-fs ${VERSION}).`);
	process.exit(0);
}

writeFileSync(readme, before + table + after);

console.log(`Measured i18n-fs ${VERSION} on ${stamp}:`);
for (const b of binaries) console.log(`  ${b.name.padEnd(8)} ${kb(b.gzip).padStart(9)} gzip`);
if (shipped) console.log(`  a client page downloads ${kb(shipped.total.gzip)} gzip in total`);
else console.log('  (run `npm run example` first to measure what an app ships)');
