// Copies the three wasm-pack outputs into the npm package.
//
// wasm-pack writes a package.json into each pkg directory; we do not want those
// nested manifests inside our own package, so only the artefacts are copied.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const from = join(root, 'crates', 'i18n-fs-wasm', 'pkg');
const to = join(root, 'packages', 'i18n-fs', 'wasm');

const TARGETS = ['edge', 'browser', 'node'];
const SKIP = new Set(['package.json', 'README.md', '.gitignore', 'LICENSE']);

if (!existsSync(from)) {
	console.error('No wasm build found. Run `pnpm wasm:build` first.');
	process.exit(1);
}

rmSync(to, { recursive: true, force: true });

for (const target of TARGETS) {
	const source = join(from, target);
	if (!existsSync(source)) {
		console.error(`Missing wasm build for ${target}. Run \`pnpm wasm:build\`.`);
		process.exit(1);
	}

	mkdirSync(join(to, target), { recursive: true });
	cpSync(source, join(to, target), {
		recursive: true,
		filter: (src) => !SKIP.has(basename(src)),
	});
}

// Embed the binaries that must not resolve a path at runtime.
//
// Neither the Node server nor the Edge runtime can be relied on to find a
// sibling file. On the server every bundler rewrites the `__dirname` such a
// lookup depends on — webpack to a chunk directory, Turbopack to a placeholder
// root — and neither copies the binary there. In the Edge runtime there is no
// base URL to resolve a relative path against at all. Both failures land at
// request time, long after the build reported success.
//
// Handing the loader the bytes removes the question, and with it every piece of
// bundler configuration an application would otherwise have to discover.
//
// The browser is excluded on purpose: there the size is genuinely paid for over
// the network, and a real `.wasm` module is both smaller than base64 and
// streamable.
const EMBEDDED = ['edge', 'node'];
const sizes = [];

for (const target of EMBEDDED) {
	const binary = readFileSync(join(to, target, 'i18n_fs_wasm_bg.wasm'));
	sizes.push(`${target} ${(binary.length / 1024).toFixed(1)} KB`);

	writeFileSync(
		join(to, target, 'bytes.mjs'),
		[
			'// Generated by scripts/sync-wasm.mjs. Do not edit.',
			`const BASE64 = '${binary.toString('base64')}';`,
			'',
			'/** The compiled core, as raw bytes. */',
			'export const wasmBytes = Uint8Array.from(atob(BASE64), (c) => c.charCodeAt(0));',
			'',
		].join('\n'),
	);

	writeFileSync(
		join(to, target, 'bytes.d.mts'),
		[
			'// Generated by scripts/sync-wasm.mjs. Do not edit.',
			'/** The compiled core, as raw bytes. */',
			'export declare const wasmBytes: Uint8Array;',
			'',
		].join('\n'),
	);
}

console.log(
	`Synced ${TARGETS.join(', ')} into packages/i18n-fs/wasm (embedded: ${sizes.join(', ')})`,
);
